name: check code for markdown issues

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - uses: DavidAnson/markdownlint-cli2-action@v23.0.0
        with:
          globs: 'content/**/**.md'
          config: '.markdownlint-cli2.jsonc'
